import { createServerClient } from "@/lib/supabase/server";
import type { EmailTier } from "@/lib/queries/tracker";

/**
 * Profile-page data loader — reads a single investor row by bare numeric id
 * from `investors_mirror` plus every partner on the firm and any
 * campaign_partners rows the current user can see (RLS-scoped). Used by
 * `/investor/[id]`. Unlike `getInvestorModalData` this is NOT bound to a
 * specific campaign_partner row — the profile is reachable by double-clicking
 * a match result before any tracker row exists.
 */

export interface InvestorProfilePartner {
  id: number;
  name: string | null;
  title: string | null;
  email: string | null;
  email_tier: EmailTier;
  linkedin: string | null;
  bio: string | null;
  focus_areas: string | null;
  is_primary_contact: boolean;
}

export interface InvestorProfileCampaignLink {
  campaign_id: string;
  campaign_name: string | null;
  partner_name: string | null;
  status_code: string | null;
  status_label: string | null;
  last_contact_at: string | null;
  days_since_last_contact: number | null;
}

export interface InvestorProfileData {
  id: number;
  firm_name: string | null;
  type: string | null;
  website: string | null;
  hq_location: string | null;
  thesis_summary: string | null;
  thesis_deep: string | null;
  stage_focus: string | null;
  sector_focus: string | null;
  geo_focus: string | null;
  cheque_min_usd: number | null;
  cheque_max_usd: number | null;
  fund_size_usd: number | null;
  actively_deploying: boolean | null;
  synthesis_confidence: string | null;
  connection_brief: string | null;
  investment_pattern: string | null;
  team_expertise: string | null;
  ideal_company_profile: string | null;
  value_add: string | null;
  recent_activity: string | null;
  linkedin_url: string | null;
  twitter_url: string | null;
  data_quality_score: number | null;
  hardware_fit_score: number | null;
  last_enriched: string | null;
  /** Legacy free-text portfolio names parsed from synthesis_data JSONB.
   *  Kept as a fallback for firms whose canonical rows haven't landed
   *  yet — gets hidden in the UI when `canonical_portfolio` has rows. */
  portfolio_companies: string[];
  /** Canonical portfolio companies linked via the
   *  `investor_portfolio_links` junction (migration 018). Each name
   *  links to /portfolio/[slug] in the UI. */
  canonical_portfolio: Array<{
    slug: string;
    name: string;
    round: string | null;
    round_at: string | null;
    amount_raw: string | null;
  }>;
  /** Other investors who share portfolio companies with this one,
   *  ranked by overlap count descending. Top 10. */
  related_firms: Array<{
    id: number;
    firm_name: string | null;
    shared_count: number;
    shared_examples: string[];
  }>;
  partners: InvestorProfilePartner[];
  campaign_links: InvestorProfileCampaignLink[];
  /** Deep dossier — Opus-generated jsonb on `investor_deep_profiles`.
   *  Null when no dossier has been generated for this investor yet.
   *  Shape: see `InvestorDeepProfile` for the documented top-level keys
   *  (free-form jsonb at the column level). */
  deep_profile: InvestorDeepProfile | null;
}

/**
 * Free-form jsonb shape on `investor_deep_profiles.profile_json`. Keys
 * are documented from a sample row (investor_id 436); the actual jsonb
 * is open-ended so the renderer treats unknown keys defensively.
 */
export interface InvestorDeepProfile {
  /** Wall-clock when the dossier was generated by the synthesiser. */
  generated_at: string | null;
  /** Echoed-from-source firm name. Used as a freshness sanity check. */
  firm_name?: string | null;
  website?: string | null;
  headquarters?: string | null;
  founding_year?: number | null;
  geo_focus?: string[] | null;
  stage_focus?: string[] | null;
  sector_focus?: string[] | null;
  /** Cheque-size envelope from the dossier, in USD. */
  tickets?: {
    minimum_usd: number | null;
    typical_usd: number | null;
    maximum_usd: number | null;
  } | null;
  fund_details?: {
    current_fund_name?: string | null;
    fund_size_usd?: number | null;
    fund_vintage?: string | null;
    fund_raised_date?: string | null;
    previous_funds?: unknown[] | null;
  } | null;
  team?: {
    total_partners?: number | null;
    managing_partners?: unknown[] | null;
    partners?: unknown[] | null;
    advisors?: unknown[] | null;
  } | null;
  social_presence?: {
    linkedin_url?: string | null;
    twitter_handle?: string | null;
    linkedin_followers?: number | null;
    twitter_followers?: number | null;
    social_activity?: string | null;
  } | null;
  investment_thesis?: {
    primary_statement?: string | null;
    detailed_description?: string | null;
    source_conflicts?: boolean | null;
  } | null;
  recent_investments?: Array<{
    company_name?: string | null;
    sector?: string | null;
    stage?: string | null;
    date?: string | null;
  }> | null;
  recent_news?: string[] | null;
  fact_checks?: Record<string, string> | null;
  quality_assessment?: {
    data_completeness?: number | null;
    source_reliability?: string | null;
    verification_level?: string | null;
  } | null;
}

function daysSince(iso: string | null | undefined): number | null {
  if (!iso) return null;
  const then = Date.parse(iso);
  if (Number.isNaN(then)) return null;
  return Math.max(0, Math.floor((Date.now() - then) / 86_400_000));
}

function parsePortfolioCompanies(synthesisData: unknown): string[] {
  if (!synthesisData || typeof synthesisData !== "object") return [];
  const bag = synthesisData as Record<string, unknown>;
  for (const key of [
    "portfolio_companies",
    "portfolio",
    "portfolio_highlights",
    "notable_investments",
  ]) {
    const value = bag[key];
    if (Array.isArray(value)) {
      const names = value
        .map((entry) => {
          if (typeof entry === "string") return entry;
          if (entry && typeof entry === "object") {
            const rec = entry as Record<string, unknown>;
            const name = rec.name ?? rec.company ?? rec.firm ?? rec.title;
            return typeof name === "string" ? name : null;
          }
          return null;
        })
        .filter((s): s is string => typeof s === "string" && s.trim().length > 0);
      if (names.length > 0) return names;
    }
  }
  return [];
}

export async function getInvestorProfile(
  investorId: number,
): Promise<InvestorProfileData | null> {
  if (!Number.isFinite(investorId)) return null;
  const supabase = await createServerClient();

  const { data: firm, error: firmErr } = await supabase
    .from("investors_mirror")
    .select(
      `id, firm_name, type, website, hq_location,
       thesis_summary, thesis_deep, stage_focus, sector_focus, geo_focus,
       cheque_min_usd, cheque_max_usd, fund_size_usd,
       actively_deploying, synthesis_data, synthesis_confidence,
       connection_brief, investment_pattern, team_expertise,
       ideal_company_profile, value_add, recent_activity,
       linkedin_url, twitter_url, data_quality_score, hardware_fit_score,
       last_enriched`,
    )
    .eq("id", investorId)
    .maybeSingle();

  if (firmErr) {
    console.error("getInvestorProfile firm fetch failed:", firmErr.message);
    return null;
  }
  if (!firm) return null;

  const { data: partnerRows, error: partnersErr } = await supabase
    .from("partners_mirror")
    .select(
      "id, name, title, email, email_tier, linkedin, bio, focus_areas, is_primary_contact",
    )
    .eq("investor_id", investorId)
    .order("is_primary_contact", { ascending: false, nullsFirst: false })
    .order("name", { ascending: true });

  if (partnersErr) {
    console.error("getInvestorProfile partners fetch failed:", partnersErr.message);
  }

  const partners: InvestorProfilePartner[] = (partnerRows ?? []).map((row) => ({
    id: row.id as number,
    name: (row.name as string | null) ?? null,
    title: (row.title as string | null) ?? null,
    email: (row.email as string | null) ?? null,
    email_tier: ((row.email_tier as string | null) ?? null) as EmailTier,
    linkedin: (row.linkedin as string | null) ?? null,
    bio: (row.bio as string | null) ?? null,
    focus_areas: (row.focus_areas as string | null) ?? null,
    is_primary_contact: Boolean(row.is_primary_contact),
  }));

  // Every campaign_partners row on any partner of this firm the current
  // user can see. RLS caps the set. We show "this investor appears in
  // N campaigns" so the profile visibly ties back into outreach state.
  const partnerIds = partners.map((p) => p.id);
  let campaignLinks: InvestorProfileCampaignLink[] = [];
  if (partnerIds.length > 0) {
    const { data: cpRows, error: cpErr } = await supabase
      .from("campaign_partners")
      .select(
        `id, partner_id, campaign_id, status_code, status_label, last_contact_at,
         campaigns:campaign_id ( id, name )`,
      )
      .in("partner_id", partnerIds)
      .order("last_contact_at", { ascending: false, nullsFirst: false });
    if (cpErr) {
      console.error("getInvestorProfile campaign_partners fetch failed:", cpErr.message);
    } else {
      const rows = (cpRows ?? []) as unknown as Array<{
        id: string;
        partner_id: number;
        campaign_id: string;
        status_code: string | null;
        status_label: string | null;
        last_contact_at: string | null;
        campaigns: { id: string; name: string | null } | null;
      }>;
      const partnerNameById = new Map(partners.map((p) => [p.id, p.name]));
      campaignLinks = rows.map((r) => ({
        campaign_id: r.campaign_id,
        campaign_name: r.campaigns?.name ?? null,
        partner_name: partnerNameById.get(r.partner_id) ?? null,
        status_code: r.status_code,
        status_label: r.status_label,
        last_contact_at: r.last_contact_at,
        days_since_last_contact: daysSince(r.last_contact_at),
      }));
    }
  }

  // Canonical portfolio companies via the investor_portfolio_links
  // junction (migration 018). These render in the UI as links to
  // /portfolio/[slug]; the legacy free-text `portfolio_companies`
  // is a fallback shown only when the canonical set is empty.
  type CanonicalPortfolio = InvestorProfileData["canonical_portfolio"];
  let canonicalPortfolio: CanonicalPortfolio = [];
  const portfolioIds: number[] = [];
  {
    const { data: portRows, error: portErr } = await supabase
      .from("investor_portfolio_links")
      .select(
        `portfolio_company_id, round, round_at, amount_raw,
         portfolio_companies:portfolio_company_id ( id, slug, name )`,
      )
      .eq("investor_id", investorId)
      .order("round_at", { ascending: false, nullsFirst: false })
      .limit(500);
    if (portErr) {
      console.error("getInvestorProfile portfolio fetch failed:", portErr.message);
    } else {
      const rows = (portRows ?? []) as unknown as Array<{
        portfolio_company_id: number;
        round: string | null;
        round_at: string | null;
        amount_raw: string | null;
        portfolio_companies: { id: number; slug: string; name: string } | null;
      }>;
      canonicalPortfolio = rows
        .filter((r) => r.portfolio_companies)
        .map((r) => ({
          slug: r.portfolio_companies!.slug,
          name: r.portfolio_companies!.name,
          round: r.round,
          round_at: r.round_at,
          amount_raw: r.amount_raw,
        }));
      for (const r of rows) {
        if (r.portfolio_company_id) portfolioIds.push(r.portfolio_company_id);
      }
    }
  }

  // Related firms = other investors sharing any portfolio company with
  // this one. Grouped + ranked client-side (portfolioIds is bounded).
  type RelatedFirms = InvestorProfileData["related_firms"];
  let relatedFirms: RelatedFirms = [];
  if (portfolioIds.length > 0) {
    const { data: relRows, error: relErr } = await supabase
      .from("investor_portfolio_links")
      .select(
        `investor_id, portfolio_company_id,
         investors_mirror:investor_id ( id, firm_name, actively_deploying ),
         portfolio_companies:portfolio_company_id ( name )`,
      )
      .in("portfolio_company_id", portfolioIds)
      .neq("investor_id", investorId);
    if (relErr) {
      console.error("getInvestorProfile related firms fetch failed:", relErr.message);
    } else {
      const rows = (relRows ?? []) as unknown as Array<{
        investor_id: number;
        portfolio_company_id: number;
        investors_mirror: {
          id: number;
          firm_name: string | null;
          actively_deploying: boolean | null;
        } | null;
        portfolio_companies: { name: string } | null;
      }>;
      // Group by other investor_id, count shared companies, keep top 3
      // example names for the hover-line.
      const bucket = new Map<
        number,
        {
          firm_name: string | null;
          shared_count: number;
          shared_examples: Set<string>;
        }
      >();
      for (const r of rows) {
        const im = r.investors_mirror;
        if (!im || im.actively_deploying !== true) continue;
        const b = bucket.get(r.investor_id) ?? {
          firm_name: im.firm_name,
          shared_count: 0,
          shared_examples: new Set<string>(),
        };
        b.shared_count += 1;
        if (r.portfolio_companies?.name && b.shared_examples.size < 3) {
          b.shared_examples.add(r.portfolio_companies.name);
        }
        bucket.set(r.investor_id, b);
      }
      relatedFirms = Array.from(bucket.entries())
        .map(([id, b]) => ({
          id,
          firm_name: b.firm_name,
          shared_count: b.shared_count,
          shared_examples: Array.from(b.shared_examples),
        }))
        .sort((a, b) => b.shared_count - a.shared_count || (a.firm_name ?? "").localeCompare(b.firm_name ?? ""))
        .slice(0, 10);
    }
  }

  // Deep dossier — Opus-generated jsonb on `investor_deep_profiles`. One
  // row per investor at most. Returns null when no dossier has been
  // synthesised yet; the view renders nothing in that case so a sparse
  // dossier never adds a hollow card to the page.
  let deepProfile: InvestorDeepProfile | null = null;
  {
    const { data: dpRow, error: dpErr } = await supabase
      .from("investor_deep_profiles")
      .select("profile_json, generated_at")
      .eq("investor_id", investorId)
      .maybeSingle();
    if (dpErr) {
      console.error(
        "getInvestorProfile deep_profile fetch failed:",
        dpErr.message,
      );
    } else if (dpRow) {
      const row = dpRow as unknown as {
        profile_json: unknown;
        generated_at: string | null;
      };
      const json =
        row.profile_json && typeof row.profile_json === "object"
          ? (row.profile_json as Record<string, unknown>)
          : {};
      // Trust the jsonb shape but type-narrow defensively. Any field that
      // doesn't match the documented shape passes through as undefined
      // and the renderer falls back to its empty-state branch.
      deepProfile = {
        ...json,
        generated_at: row.generated_at,
      } as InvestorDeepProfile;
    }
  }

  const firmRow = firm as unknown as {
    id: number;
    firm_name: string | null;
    type: string | null;
    website: string | null;
    hq_location: string | null;
    thesis_summary: string | null;
    thesis_deep: string | null;
    stage_focus: string | null;
    sector_focus: string | null;
    geo_focus: string | null;
    cheque_min_usd: number | null;
    cheque_max_usd: number | null;
    fund_size_usd: number | null;
    actively_deploying: boolean | null;
    synthesis_data: unknown;
    synthesis_confidence: string | null;
    connection_brief: string | null;
    investment_pattern: string | null;
    team_expertise: string | null;
    ideal_company_profile: string | null;
    value_add: string | null;
    recent_activity: string | null;
    linkedin_url: string | null;
    twitter_url: string | null;
    data_quality_score: number | null;
    hardware_fit_score: number | null;
    last_enriched: string | null;
  };

  return {
    id: firmRow.id,
    firm_name: firmRow.firm_name,
    type: firmRow.type,
    website: firmRow.website,
    hq_location: firmRow.hq_location,
    thesis_summary: firmRow.thesis_summary,
    thesis_deep: firmRow.thesis_deep,
    stage_focus: firmRow.stage_focus,
    sector_focus: firmRow.sector_focus,
    geo_focus: firmRow.geo_focus,
    cheque_min_usd: firmRow.cheque_min_usd,
    cheque_max_usd: firmRow.cheque_max_usd,
    fund_size_usd: firmRow.fund_size_usd,
    actively_deploying: firmRow.actively_deploying,
    synthesis_confidence: firmRow.synthesis_confidence,
    connection_brief: firmRow.connection_brief,
    investment_pattern: firmRow.investment_pattern,
    team_expertise: firmRow.team_expertise,
    ideal_company_profile: firmRow.ideal_company_profile,
    value_add: firmRow.value_add,
    recent_activity: firmRow.recent_activity,
    linkedin_url: firmRow.linkedin_url,
    twitter_url: firmRow.twitter_url,
    data_quality_score: firmRow.data_quality_score,
    hardware_fit_score: firmRow.hardware_fit_score,
    last_enriched: firmRow.last_enriched,
    portfolio_companies: parsePortfolioCompanies(firmRow.synthesis_data),
    canonical_portfolio: canonicalPortfolio,
    related_firms: relatedFirms,
    partners,
    campaign_links: campaignLinks,
    deep_profile: deepProfile,
  };
}
